In [2]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving dataset_Facebook.csv to dataset_Facebook (1).csv


In [3]:
import pandas as pd
import io
  
df = pd.read_csv(io.BytesIO(uploaded['dataset_Facebook.csv']),sep = ';')
#print(df)

df.head(5)

Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0            139441   Photo         2          12             4          3   
1            139441  Status         2          12             3         10   
2            139441   Photo         3          12             3          3   
3            139441   Photo         2          12             2         10   
4            139441   Photo         2          12             2          3   

   Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0   0.0                       2752                             5091   
1   0.0                      10460                            19057   
2   0.0                       2413                             4373   
3   1.0                      50128                            87991   
4   0.0                       7244                            13594   

   Lifetime Engaged Users  Lifetime Post Consumers  \
0                     178                      109   
1                    1457                     1361   
2                     177                      113   
3                    2211                      790   
4                     671                      410   

   Lifetime Post Consumptions  \
0                         159   
1                        1674   
2                         154   
3                        1119   
4                         580   

   Lifetime Post Impressions by people who have liked your Page  \
0                                               3078              
1                                              11710              
2                                               2812              
3                                              61027              
4                                               6228              

   Lifetime Post reach by people who like your Page  \
0                                              1640   
1                                              6112   
2                                              1503   
3                                             32048   
4                                              3200   

   Lifetime People who have liked your Page and engaged with your post  \
0                                                119                     
1                                               1108                     
2                                                132                     
3                                               1386                     
4                                                396                     

   comment    like  share  Total Interactions  
0        4    79.0   17.0                 100  
1        5   130.0   29.0                 164  
2        0    66.0   14.0                  80  
3       58  1572.0  147.0                1777  
4       19   325.0   49.0                 393

In [ ]:
df['Type']

0       Photo
1      Status
2       Photo
3       Photo
4       Photo
        ...  
495     Photo
496     Photo
497     Photo
498     Photo
499     Photo
Name: Type, Length: 500, dtype: object

In [ ]:
print(df.columns)

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')


In [ ]:
df[['Type','Category']]

Type  Category
0     Photo         2
1    Status         2
2     Photo         3
3     Photo         2
4     Photo         2
..      ...       ...
495   Photo         3
496   Photo         2
497   Photo         1
498   Photo         3
499   Photo         2

[500 rows x 2 columns]

In [ ]:
df_subset = df[['like','share']]

print(df_subset)

       like  share
0      79.0   17.0
1     130.0   29.0
2      66.0   14.0
3    1572.0  147.0
4     325.0   49.0
..      ...    ...
495    53.0   26.0
496    53.0   22.0
497    93.0   18.0
498    91.0   38.0
499    91.0   28.0

[500 rows x 2 columns]


In [ ]:
df_subset1 = df[df['like']>100]

print(df_subset1)

     Page total likes    Type  Category  ...    like  share  Total Interactions
1              139441  Status         2  ...   130.0   29.0                 164
3              139441   Photo         2  ...  1572.0  147.0                1777
4              139441   Photo         2  ...   325.0   49.0                 393
5              139441  Status         2  ...   152.0   33.0                 186
6              139441   Photo         3  ...   249.0   27.0                 279
..                ...     ...       ...  ...     ...    ...                 ...
488             85979   Photo         3  ...   277.0   80.0                 378
491             85979   Photo         3  ...   105.0   46.0                 152
492             85979    Link         1  ...   128.0    9.0                 137
493             85093   Photo         3  ...   185.0   55.0                 257
494             85093   Photo         3  ...   125.0   41.0                 176

[252 rows x 19 columns]


In [ ]:
df.loc[1]

Page total likes                                                       139441
Type                                                                   Status
Category                                                                    2
Post Month                                                                 12
Post Weekday                                                                3
Post Hour                                                                  10
Paid                                                                      0.0
Lifetime Post Total Reach                                               10460
Lifetime Post Total Impressions                                         19057
Lifetime Engaged Users                                                   1457
Lifetime Post Consumers                                                  1361
Lifetime Post Consumptions                                               1674
Lifetime Post Impressions by people who have liked your Page    

In [ ]:
df.loc[[1,5,7,8]]

Page total likes    Type  Category  ...   like  share  Total Interactions
1            139441  Status         2  ...  130.0   29.0                 164
5            139441  Status         2  ...  152.0   33.0                 186
7            139441   Photo         3  ...  325.0   14.0                 339
8            139441  Status         2  ...  161.0   31.0                 192

[4 rows x 19 columns]

In [ ]:
df.loc[1:7,['like','share']]

like  share
1   130.0   29.0
2    66.0   14.0
3  1572.0  147.0
4   325.0   49.0
5   152.0   33.0
6   249.0   27.0
7   325.0   14.0

In [ ]:
df.sort_values(by = "like",ascending= False)

Page total likes   Type  Category  ...    like  share  Total Interactions
244            130791  Photo         2  ...  5172.0  790.0                6334
379            111620  Photo         3  ...  1998.0  128.0                2177
349            117764  Photo         3  ...  1639.0  122.0                1806
168            135428  Photo         1  ...  1622.0  208.0                1974
3              139441  Photo         2  ...  1572.0  147.0                1777
..                ...    ...       ...  ...     ...    ...                 ...
21             138414  Photo         1  ...     0.0    0.0                   0
100            137020  Photo         1  ...     0.0    0.0                   0
441             98195  Photo         1  ...     0.0    0.0                   0
417            104070  Photo         1  ...     0.0    0.0                   0
111            136736  Photo         1  ...     NaN    NaN                   0

[500 rows x 19 columns]

In [ ]:
df.sort_values("like")

Page total likes   Type  Category  ...    like  share  Total Interactions
21             138414  Photo         1  ...     0.0    0.0                   0
417            104070  Photo         1  ...     0.0    0.0                   0
100            137020  Photo         1  ...     0.0    0.0                   0
76             137893  Photo         1  ...     0.0    0.0                   0
441             98195  Photo         1  ...     0.0    0.0                   0
..                ...    ...       ...  ...     ...    ...                 ...
168            135428  Photo         1  ...  1622.0  208.0                1974
349            117764  Photo         3  ...  1639.0  122.0                1806
379            111620  Photo         3  ...  1998.0  128.0                2177
244            130791  Photo         2  ...  5172.0  790.0                6334
111            136736  Photo         1  ...     NaN    NaN                   0

[500 rows x 19 columns]

In [ ]:
df.sort_values(by = "like",ascending= False, kind="mergesort")

Page total likes   Type  Category  ...    like  share  Total Interactions
244            130791  Photo         2  ...  5172.0  790.0                6334
379            111620  Photo         3  ...  1998.0  128.0                2177
349            117764  Photo         3  ...  1639.0  122.0                1806
168            135428  Photo         1  ...  1622.0  208.0                1974
3              139441  Photo         2  ...  1572.0  147.0                1777
..                ...    ...       ...  ...     ...    ...                 ...
76             137893  Photo         1  ...     0.0    0.0                   0
100            137020  Photo         1  ...     0.0    0.0                   0
417            104070  Photo         1  ...     0.0    0.0                   0
441             98195  Photo         1  ...     0.0    0.0                   0
111            136736  Photo         1  ...     NaN    NaN                   0

[500 rows x 19 columns]

In [ ]:
df.sort_values(by=["like", "share"])

Page total likes   Type  Category  ...    like  share  Total Interactions
21             138414  Photo         1  ...     0.0    0.0                   0
76             137893  Photo         1  ...     0.0    0.0                   0
100            137020  Photo         1  ...     0.0    0.0                   0
417            104070  Photo         1  ...     0.0    0.0                   0
441             98195  Photo         1  ...     0.0    0.0                   0
..                ...    ...       ...  ...     ...    ...                 ...
168            135428  Photo         1  ...  1622.0  208.0                1974
349            117764  Photo         3  ...  1639.0  122.0                1806
379            111620  Photo         3  ...  1998.0  128.0                2177
244            130791  Photo         2  ...  5172.0  790.0                6334
111            136736  Photo         1  ...     NaN    NaN                   0

[500 rows x 19 columns]

In [ ]:
result = df.transpose()
print(result)

                                                       0    ...    499
Page total likes                                    139441  ...  81370
Type                                                 Photo  ...  Photo
Category                                                 2  ...      2
Post Month                                              12  ...      1
Post Weekday                                             4  ...      4
Post Hour                                                3  ...      4
Paid                                                   0.0  ...    NaN
Lifetime Post Total Reach                             2752  ...   4188
Lifetime Post Total Impressions                       5091  ...   7292
Lifetime Engaged Users                                 178  ...    564
Lifetime Post Consumers                                109  ...    524
Lifetime Post Consumptions                             159  ...    743
Lifetime Post Impressions by people who have li...    3078  ...   3861
Lifeti

In [ ]:
df.shape

(500, 19)

For shape


In [ ]:
selective_df = pd.DataFrame(df,columns =['like','share','Category','Type'])

selective_df.head(5)


like  share  Category    Type
0    79.0   17.0         2   Photo
1   130.0   29.0         2  Status
2    66.0   14.0         3   Photo
3  1572.0  147.0         2   Photo
4   325.0   49.0         2   Photo

In [ ]:
pivot_table = pd.pivot_table(selective_df,index= ['Category','like'])

print(pivot_table)

                      share
Category like              
1        0.0       0.000000
         1.0       2.000000
         2.0       0.000000
         3.0       0.666667
         4.0       1.000000
...                     ...
3        1155.0  102.000000
         1372.0   47.000000
         1546.0  181.000000
         1639.0  122.000000
         1998.0  128.000000

[368 rows x 1 columns]


In [ ]:
pivot_table.shape

(368, 1)

In [ ]:
pivot_table.reset_index(inplace=True)

pivot_table

Category    like       share
0           1     0.0    0.000000
1           1     1.0    2.000000
2           1     2.0    0.000000
3           1     3.0    0.666667
4           1     4.0    1.000000
..        ...     ...         ...
363         3  1155.0  102.000000
364         3  1372.0   47.000000
365         3  1546.0  181.000000
366         3  1639.0  122.000000
367         3  1998.0  128.000000

[368 rows x 3 columns]

In [ ]:
pivot_table.melt(id_vars=['like','share'])

like       share  variable  value
0       0.0    0.000000  Category      1
1       1.0    2.000000  Category      1
2       2.0    0.000000  Category      1
3       3.0    0.666667  Category      1
4       4.0    1.000000  Category      1
..      ...         ...       ...    ...
363  1155.0  102.000000  Category      3
364  1372.0   47.000000  Category      3
365  1546.0  181.000000  Category      3
366  1639.0  122.000000  Category      3
367  1998.0  128.000000  Category      3

[368 rows x 4 columns]

In [ ]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32], 
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']} 


data2 = {'Name':['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'], 
        'Age':[17, 14, 12, 52], 
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'], 
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']} 

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])

print(df, "\n\n", df1) 

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd 

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons


In [ ]:
frames = [df, df1]
res1 = pd.concat(frames)
res1

Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [ ]:
df_new = pd.DataFrame(data1,index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[2, 3, 6, 7]) 

print(df, "\n\n", df1) 


res2 = pd.concat([df, df1], axis=1, join='inner')


res2

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd 

      Name  Age    Address Qualification
2    Abhi   17     Nagpur         Btech
3  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons


Name  Age    Address Qualification    Name  Age Address Qualification
2  Gaurav   22  Allahabad           MCA    Abhi   17  Nagpur         Btech
3    Anuj   32    Kannuaj           Phd  Ayushi   14  Kanpur           B.A

In [ ]:
# Define a dictionary containing employee data 
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32],} 
   
# Define a dictionary containing employee data 
data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'], 
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']} 
 
# Convert the dictionary into DataFrame  
df = pd.DataFrame(data1)
 
# Convert the dictionary into DataFrame  
df1 = pd.DataFrame(data2) 
  
 
print(df, "\n\n", df1) 

res = pd.merge(df, df1, on='key')
res



  key    Name  Age
0  K0     Jai   27
1  K1  Princi   24
2  K2  Gaurav   22
3  K3    Anuj   32 

   key    Address Qualification
0  K0     Nagpur         Btech
1  K1     Kanpur           B.A
2  K2  Allahabad          Bcom
3  K3    Kannuaj        B.hons


key    Name  Age    Address Qualification
0  K0     Jai   27     Nagpur         Btech
1  K1  Princi   24     Kanpur           B.A
2  K2  Gaurav   22  Allahabad          Bcom
3  K3    Anuj   32    Kannuaj        B.hons

In [ ]:
# Define a dictionary containing employee data 
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32],} 
   
# Define a dictionary containing employee data 
data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'], 
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']} 
 
# Convert the dictionary into DataFrame  
df = pd.DataFrame(data1)
 
# Convert the dictionary into DataFrame  
df1 = pd.DataFrame(data2) 
  
 
print(df, "\n\n", df1) 

# merging dataframe using multiple keys
res1 = pd.merge(df, df1, on=['key', 'key1'])
 
res1

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32 

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons


key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

In [ ]:
import pandas as pd
left = pd.DataFrame({
         'id':[1,2,3,4,5],
         'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
         'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame(
         {'id':[1,2,3,4,5],
         'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
         'subject_id':['sub2','sub4','sub3','sub6','sub5']})
print(pd.merge(left,right,on='id'))

   id  Name_x subject_id_x Name_y subject_id_y
0   1    Alex         sub1  Billy         sub2
1   2     Amy         sub2  Brian         sub4
2   3   Allen         sub4   Bran         sub3
3   4   Alice         sub6  Bryce         sub6
4   5  Ayoung         sub5  Betty         sub5


In [ ]:
import pandas as pd
left = pd.DataFrame({
   'id':[1,2,3,4,5],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame({
	'id':[1,2,3,4,5],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5']})
print(pd.merge(left,right,on=['id','subject_id']))

   id  Name_x subject_id Name_y
0   4   Alice       sub6  Bryce
1   5  Ayoung       sub5  Betty


In [ ]:
# Python Program illustrating
# numpy.reshape() method

import numpy as geek

# array = geek.arrange(8)
# The 'numpy' module has no attribute 'arrange'
array1 = geek.arange(8)
print("Original array : \n", array1)

# shape array with 2 rows and 4 columns
array2 = geek.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n",
	array2)

# shape array with 4 rows and 2 columns
array3 = geek.arange(8).reshape(4, 2)
print("\narray reshaped with 2 rows and 4 columns : \n",
	array3)

# Constructs 3D array
array4 = geek.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n",
	array4)


Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# Python Programming illustrating
# numpy.arange method

import numpy as geek

print("A\n", geek.arange(4).reshape(2, 2), "\n")
print("A\n", geek.arange(4, 10), "\n")
print("A\n", geek.arange(4, 20, 3), "\n")


A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



In [ ]:
# Python Programming illustrating
# numpy.arange method

import numpy as np

# Printing all numbers from 1 to
# 2 in steps of 0.1
print(np.arange(1, 2, 0.1))


[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [ ]:
import numpy as np 
 
arr = np.arange(16) 
print("Array elements: \n", arr) 
 
res = np.arange(16).reshape(4, 4) 
print("\nArray reshaped as 4 rows and 4 columns: \n", res) 

Array elements: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Array reshaped as 4 rows and 4 columns: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Example
Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Example
Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elemen

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Create a simple dataframe

# importing pandas as pd
import pandas as pd

# creating a dataframe
df = pd.DataFrame({'Name': {0: 'John', 1: 'Bob', 2: 'Shiela'},
				'Course': {0: 'Masters', 1: 'Graduate', 2: 'Graduate'},
				'Age': {0: 27, 1: 23, 2: 21}})
df


Name    Course  Age
0    John   Masters   27
1     Bob  Graduate   23
2  Shiela  Graduate   21

In [ ]:
# Name is id_vars and Course is value_vars
pd.melt(df, id_vars =['Name'], value_vars =['Course'])


Name variable     value
0    John   Course   Masters
1     Bob   Course  Graduate
2  Shiela   Course  Graduate

In [ ]:
# multiple unpivot columns
pd.melt(df, id_vars =['Name'], value_vars =['Course', 'Age'])


Name variable     value
0    John   Course   Masters
1     Bob   Course  Graduate
2  Shiela   Course  Graduate
3    John      Age        27
4     Bob      Age        23
5  Shiela      Age        21

In [4]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving data.csv to data.csv


In [10]:
import pandas as pd
import io
  
newdf = pd.read_csv(io.BytesIO(uploaded['data.csv']),sep = ',')
#print(newdf)

#newdf.head(5)
df2 = newdf.melt()
#df2=pd.melt(newdf, id_vars =['Duration'], value_vars =['Pulse'])
#df2.head(5)
print(df2.to_string())
#Note that we use the to_string() method to return the entire DataFrame.

     variable   value
0    Duration    60.0
1    Duration    60.0
2    Duration    60.0
3    Duration    45.0
4    Duration    45.0
5    Duration    60.0
6    Duration    60.0
7    Duration    45.0
8    Duration    30.0
9    Duration    60.0
10   Duration    60.0
11   Duration    60.0
12   Duration    60.0
13   Duration    60.0
14   Duration    60.0
15   Duration    60.0
16   Duration    60.0
17   Duration    45.0
18   Duration    60.0
19   Duration    45.0
20   Duration    60.0
21   Duration    45.0
22   Duration    60.0
23   Duration    45.0
24   Duration    60.0
25   Duration    60.0
26   Duration    60.0
27   Duration    60.0
28   Duration    60.0
29   Duration    60.0
30   Duration    60.0
31   Duration    45.0
32   Duration    60.0
33   Duration    60.0
34   Duration    60.0
35   Duration    60.0
36   Duration    60.0
37   Duration    60.0
38   Duration    60.0
39   Duration    45.0
40   Duration    45.0
41   Duration    60.0
42   Duration    60.0
43   Duration    60.0
44   Durat

In [ ]:
import pandas as pd
import numpy as np

#Create a DataFrame
d = {
    'countries':['A','B','C'],
    'population_in_million':[100,200,120],
    'gdp_percapita':[2000,7000,15000]
    }

df = pd.DataFrame(d,columns=['countries','population_in_million','gdp_percapita'])
df

countries  population_in_million  gdp_percapita
0         A                    100           2000
1         B                    200           7000
2         C                    120          15000

In [ ]:
# shape from wide to long with melt function in pandas

df2=pd.melt(df,id_vars=['countries'],var_name='metrics', value_name='values')
df2

#data frame “df” is passed to melt() function
#id_vars is the variable which need to be left unaltered which is “countries”
#var_name are the column names so we named it as ‘metrics’
#value_name are its values so we named it as ‘values’

countries                metrics  values
0         A  population_in_million     100
1         B  population_in_million     200
2         C  population_in_million     120
3         A          gdp_percapita    2000
4         B          gdp_percapita    7000
5         C          gdp_percapita   15000

In [ ]:
#Reshaping a data from long to wide in python pandas is done with pivot() function.
import pandas as pd
import numpy as np

#Create a DataFrame
d = {
    'countries':['A','B','C','A','B','C'],
    'metrics':['population_in_million','population_in_million','population_in_million',
                             'gdp_percapita','gdp_percapita','gdp_percapita'],
    'values':[100,200,120,2000,7000,15000]
    }

df = pd.DataFrame(d,columns=['countries','metrics','values'])
df


countries                metrics  values
0         A  population_in_million     100
1         B  population_in_million     200
2         C  population_in_million     120
3         A          gdp_percapita    2000
4         B          gdp_percapita    7000
5         C          gdp_percapita   15000

In [ ]:
# reshape from long to wide in pandas python

df2=df.pivot(index='countries', columns='metrics', values='values')
df2

metrics    gdp_percapita  population_in_million
countries                                      
A                   2000                    100
B                   7000                    200
C                  15000                    120

In [ ]:
import pandas as pd1
import io
df_wide = pd1.DataFrame(
  {"student": ["Andy", "Bernie", "Cindy", "Deb"],
   "school":  ["Z", "Y", "Z", "Y"],
   "english": [10, 100, 1000, 10000],  # eng grades
   "math":    [20, 200, 2000, 20000],  # math grades
   "physics": [30, 300, 3000, 30000]   # physics grades
  }
)
df_wide

student school  english   math  physics
0    Andy      Z       10     20       30
1  Bernie      Y      100    200      300
2   Cindy      Z     1000   2000     3000
3     Deb      Y    10000  20000    30000

In [ ]:
df_wide.melt(id_vars=["student", "school"],
             var_name="cLaSs",
             value_name="gRaDe")

student school    cLaSs  gRaDe
0     Andy      Z  english     10
1   Bernie      Y  english    100
2    Cindy      Z  english   1000
3      Deb      Y  english  10000
4     Andy      Z     math     20
5   Bernie      Y     math    200
6    Cindy      Z     math   2000
7      Deb      Y     math  20000
8     Andy      Z  physics     30
9   Bernie      Y  physics    300
10   Cindy      Z  physics   3000
11     Deb      Y  physics  30000

In [ ]:
#Melt2 example
df_wide.melt(id_vars="student", 
             value_vars=["english","math"], 
             var_name="cLaSs", 
             value_name="gRaDe")

student    cLaSs  gRaDe
0    Andy  english     10
1  Bernie  english    100
2   Cindy  english   1000
3     Deb  english  10000
4    Andy     math     20
5  Bernie     math    200
6   Cindy     math   2000
7     Deb     math  20000

In [ ]:
df_wide.melt(id_vars="student",
             var_name="cLaSs",
             value_name="gRaDe")

student    cLaSs  gRaDe
0     Andy   school      Z
1   Bernie   school      Y
2    Cindy   school      Z
3      Deb   school      Y
4     Andy  english     10
5   Bernie  english    100
6    Cindy  english   1000
7      Deb  english  10000
8     Andy     math     20
9   Bernie     math    200
10   Cindy     math   2000
11     Deb     math  20000
12    Andy  physics     30
13  Bernie  physics    300
14   Cindy  physics   3000
15     Deb  physics  30000

In [ ]:
#Long to wide 
df_long = pd1.DataFrame({
        "student":
            ["Andy", "Bernie", "Cindy", "Deb",
             "Andy", "Bernie", "Cindy", "Deb",
             "Andy", "Bernie", "Cindy", "Deb"],
        "school":
            ["Z", "Y", "Z", "Y",
             "Z", "Y", "Z", "Y",
             "Z", "Y", "Z", "Y"],
        "class":
            ["english", "english", "english", "english",
             "math", "math", "math", "math",
             "physics", "physics", "physics", "physics"],
        "grade":
            [10, 100, 1000, 10000,
             20, 200, 2000, 20000,
             30, 300, 3000, 30000]
})
print(df_long)

   student school    class  grade
0     Andy      Z  english     10
1   Bernie      Y  english    100
2    Cindy      Z  english   1000
3      Deb      Y  english  10000
4     Andy      Z     math     20
5   Bernie      Y     math    200
6    Cindy      Z     math   2000
7      Deb      Y     math  20000
8     Andy      Z  physics     30
9   Bernie      Y  physics    300
10   Cindy      Z  physics   3000
11     Deb      Y  physics  30000


In [ ]:
df_long.pivot_table(index=["student", "school"], 
                    columns='class', 
                    values='grade')

class           english   math  physics
student school                         
Andy    Z            10     20       30
Bernie  Y           100    200      300
Cindy   Z          1000   2000     3000
Deb     Y         10000  20000    30000

In [ ]:
#Example 2
#You can also aggregate each resulting row and column by specifying margins=True (default False).
df_long.pivot_table(index=["student", "school"], 
                    columns='class', 
                    values='grade',
                    margins=True,  # add margins
                    aggfunc='sum')  # sum margins (rows/columns)
                    #Here we aggregate by computing the sum via aggfunc='sum' (default 'mean').
                    #There are many other aggregation functions you can use (e.g.,'median' 'sum' 'max'). 
                    #You can also specify multiple functions as a list (e.g.,aggfunc=['mean', 'sum']).

class           english   math  physics    All
student school                                
Andy    Z            10     20       30     60
Bernie  Y           100    200      300    600
Cindy   Z          1000   2000     3000   6000
Deb     Y         10000  20000    30000  60000
All               11110  22220    33330  66660

In [ ]:
#The final example shows you what happens when you pivot multiple columns (columns=['school', 'class']) and
# you can also deal with missing values after pivoting by replacing the NaN values with another value (-5 in the example below).
df_long.pivot_table(index="student", 
                    columns=['school', 'class'], 
                    values='grade', 
                    fill_value=-5)  # replace NaN with -5

school        Y                      Z              
class   english   math physics english  math physics
student                                             
Andy         -5     -5      -5      10    20      30
Bernie      100    200     300      -5    -5      -5
Cindy        -5     -5      -5    1000  2000    3000
Deb       10000  20000   30000      -5    -5      -5